### ISSUE TITLE
Just run provider and error occur

### ISSUE THREAD

**Issue by hwangjr** [nikosch86/stf-poc#8]
Hi, thanks for your compose script, and i just run `provider` on centos, but i found error, it seems like `stf-poc_adb` container can't find `adb` command:

Here is the script:
```
version: '2'

volumes:
  storage-temp:

services:
  adb:
    image: sorccu/adb:latest
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
  triproxy:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf triproxy app --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
  dev-triproxy:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf triproxy dev --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
  provider:
    image: openstf/stf:latest
    restart: unless-stopped
    command: stf provider --name ${STATION_NAME} --connect-sub tcp://dev-triproxy:7250 --connect-push tcp://dev-triproxy:7270 --storage-url http://${PUBLIC_IP}/ --public-ip ${PUBLIC_IP} --heartbeat-interval 10000 --screen-ws-url-pattern "ws://${PUBLIC_IP}/d/nuc/3RP4C18102010991/5037/" --min-port 7400 --max-port 7700
    ports:
      - 7400-7700:7400-7700
    depends_on:
      - adb
      - dev-triproxy
      - triproxy
      - storage-temp
  storage-temp:
    build: storage-temp/
    restart: unless-stopped
    volumes:
      - storage-temp:/app/data
    command: stf storage-temp --port 3000 --save-dir /app/data
```

Here is the logs:
```
[root@centos-linux stf-poc]# docker logs 95b4a4b3ad13
2018-10-04T14:05:42.196Z INF/provider 1 [*] Subscribing to permanent channel "Gi/y/mjIQJGB8K+e5U3g7w=="
2018-10-04T14:05:42.211Z INF/provider 1 [*] Sending output to "tcp://dev-triproxy:7270"
2018-10-04T14:05:42.212Z INF/provider 1 [*] Receiving input from "tcp://dev-triproxy:7250"
Unhandled rejection Error: spawn adb ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Here is the docker containers:
```
[root@centos-linux stf-poc]# docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS              PORTS                                        NAMES
95b4a4b3ad13        openstf/stf:latest     "stf provider --name…"   About a minute ago   Up About a minute   3000/tcp, 0.0.0.0:7400-7700->7400-7700/tcp   stf-poc_provider_1
10b69fd77d16        stf-poc_storage-temp   "stf storage-temp --…"   About a minute ago   Up About a minute   3000/tcp                                     stf-poc_storage-temp_1
b93d8ec34596        sorccu/adb:latest      "/sbin/tini -- adb -…"   About a minute ago   Up About a minute   5037/tcp                                     stf-poc_adb_1
07b774599f3c        openstf/stf:latest     "stf triproxy dev --…"   About a minute ago   Up About a minute   3000/tcp                                     stf-poc_dev-triproxy_1
14622a0b5fd0        openstf/stf:latest     "stf triproxy app --…"   About a minute ago   Up About a minute   3000/tcp                                     stf-poc_triproxy_1
```
